name: CI

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: go build -o product-catalog-service src/product-catalog/main.go

      - name: UnitTest
        run: go test src/product-catalog/...
  code-quality:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        run: |
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2
              golangci-lint run src/product-catalog/...
  docker:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Install Docker
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: src/product-catalog
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/product-catalog:${{ github.run_id }}

  update-k8s:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update tag in Kubernetes deployment
        run: |
          sed -i "s/image: .*/image: ${{ secrets.DOCKERHUB_USERNAME }}/prdocut-catalog:${{ github.run_id }}/" kubernetes/productcatalog/deploy.yaml
      - name: git commit
        run: |
          git config --global user.email "gogulanikhil@gmail.com"
          git config --global user.name "gogulanikhil"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "Update deployment image tag"
          git push